defaults: &defaults
  serviceName: image-handler-test
  offlinePort: 8080
  region: 'us-east-1'
  environment: &defaults.environment
    ALLOWED_SIZES: '642x0,100x100,200x200,800x800,1600x0'
    DEFAULT_TO_FIRST_SIZE: 'Yes'
    AUTO_WEBP: 'Yes'
    CORS_ENABLED: 'No'
    CORS_ORIGIN: '*'

stages:
  dev:
    <<: *defaults
    environment:
      <<: *defaults.environment
      SOURCE_BUCKETS: 'bucket-name'
      SECURITY_KEY: ''